name: Actualizar Binance P2P

on:
  schedule:
    # Se ejecuta cada 15 minutos de cada hora
    - cron: '*/15 * * * *'
  workflow_dispatch: # Permite ejecutarlo manualmente para pruebas

jobs:
  update-binance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: pip install requests supabase
          
      - name: Ejecutar script Binance
        run: python dolar_backend/binance_service.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
