name: Actualizar Tasas Automáticamente
on:
  schedule:
    - cron: '*/15 * * * *' # Esto le dice a GitHub: "ejecútalo cada 15 minutos"
  workflow_dispatch: # Esto permite que tú lo ejecutes manualmente desde el botón de la web

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Instalar dependencias
        run: pip install supabase python-dotenv
      - name: Ejecutar Extractor
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          echo "Contenido de la carpeta actual:"
          ls -R
          echo "Intentando ejecutar extractor..."
          python extractor.py || python dolar_backend/extractor.py
